### ISSUE TITLE
请教下刷新页面会出现404页面闪烁

### ISSUE THREAD

**Issue by beclass** [hequan2017/seal-vue#1]
大佬指点下刷新页面会出现404页面闪烁的问题
![vadmin](https://user-images.githubusercontent.com/12541388/59018375-567d0e00-8878-11e9-909c-9ca2e4bd25e7.gif)

**Comment by hequan2017** [comment]
我用demo测试 没发现这个问题， 刷新的时候 会白屏幕一下。 不会显示404

**Comment by hequan2017** [comment]
我这边没有复现这个问题， 具体 得看一下 刷新的逻辑。

**Comment by beclass** [comment]
好了

**Comment by beclass** [comment]
请教下，这样如果有二级菜单有问题呢
![image](https://user-images.githubusercontent.com/12541388/59346959-115c4e80-8d46-11e9-9684-2b840dd2fcdc.png)
