### ISSUE TITLE
请教下刷新页面二级菜单选中的问题

### ISSUE THREAD

**Issue by beclass** [hequan2017/seal-vue#2]
当选中菜单为二级菜单子菜单的时候，刷新一下页面，菜单不会回到选中的状态，且再展开二级菜单需要点击2次。
![menu](https://user-images.githubusercontent.com/12541388/60147656-e8859000-9800-11e9-9e8e-45ecd4fb883d.gif)

**Comment by hequan2017** [comment]
这个问题 可能是  是因为 刷新时，我重新加载了菜单造成的。

你可以去看下 iview-admin

**Comment by beclass** [comment]
我在routers.js的otherRouter下添加
{
    path: '*',
    name: 'error_404',
    meta: {
      hideInMenu: true
    },
    component: () => import('@/view/error-page/404.vue')
  }
并且取消加载
// 作为Main组件的子页面展示并且在左侧菜单显示的路由写在appRouter里
// export const appRouter = [...dynamicRouterAdd()]
// export const routes = [...otherRouter, ...mainRouter, ...appRouter]  
   export const routes = [...otherRouter, ...mainRouter]
刷新页面就不会出现上面那个问题。但又回到之前那个问题了，就是会先出现0.1秒的404页面闪烁，目前解决办法是，舍弃404效果，把内容为空，
![menu](https://user-images.githubusercontent.com/12541388/60150408-343d3700-980b-11e9-8f9d-2ab018b2cc79.gif)

**Comment by hequan2017** [comment]
回头我看看，最近在忙别的。

**Comment by beclass** [comment]
辛苦大佬
